language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  app: TuringGameNightAPI
  api_key:
    secure: HEROKU_DEPLOY_KEY
  on:
    repo: TuringGameNight/Back-End
  run: rails db:migrate
